#!/usr/bin/env python3
"""
MCP server for Test Demo Project documentation.

This server provides semantic search capabilities over the project documentation
through the Model Context Protocol (MCP).

Generated by DocRAG Kit.
"""

import asyncio
import sys
from pathlib import Path

# Add parent directory to path to import docrag
sys.path.insert(0, str(Path(__file__).parent.parent))

from docrag.mcp_server import MCPServer


async def main():
    """Main entry point for MCP server."""
    try:
        # Initialize server with project root
        project_root = Path(__file__).parent.parent
        server = MCPServer(config_path=project_root / ".docrag")
        
        # Run server
        await server.run()
    except Exception as e:
        print(f"❌ Failed to start MCP server: {e}", file=sys.stderr)
        raise


if __name__ == "__main__":
    asyncio.run(main())
