#!/usr/bin/env python3
"""
MCP Server wrapper for this project.

This file is auto-generated by DocRAG Kit.
It provides a simple entry point for the MCP server.

Usage:
    python mcp_server.py
    
Or configure in Kiro AI's MCP settings.
"""

import asyncio
import sys
from pathlib import Path

# Add parent directory to path to import docrag
sys.path.insert(0, str(Path(__file__).parent.parent))

from docrag.mcp_server import MCPServer


async def main():
    """Run MCP server for this project."""
    try:
        # Initialize server with current directory
        server = MCPServer(config_path=Path(__file__).parent)
        await server.run()
    except Exception as e:
        print(f"❌ Failed to start MCP server: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    asyncio.run(main())
