#!/usr/bin/env python3
"""
MCP Server wrapper for this project.

This file is auto-generated by DocRAG Kit.

IMPORTANT: This wrapper should be run via the installed docrag package:
    python -m docrag.mcp_server
    
NOT directly as a script (relative imports won't work):
    python .docrag/mcp_server.py  # ERROR: Don't do this

For MCP configuration, use:
    docrag mcp-config
"""

import sys
from pathlib import Path

print("WARNING:  WARNING: This wrapper is deprecated!", file=sys.stderr)
print("   Use 'python -m docrag.mcp_server' instead", file=sys.stderr)
print("   Or run 'docrag mcp-config' to update your MCP configuration", file=sys.stderr)
sys.exit(1)
